### ISSUE TITLE
What kinds of data to be shown

### ISSUE THREAD

**Issue by xpgeng** [GNYIO/gny-explorer#2]
What kinds of data to be shown on the explorer

- Basic
    - number of blocks
    - number of transactions
    - number of delegates
    - Statics
        - Blockchain size
        - Latest block height
        - number of nodes
    - 24h statics
        - average transaction fee
        - number of transactions
- Latest blocks table
    - height
    - id
    - time
    - amount
    - delegate
- Biggest transactions table
    - block id
    - transaction id
    - time
    - amount

**Comment by a1300** [comment]
@xpgeng great overview

Currently I don't think it is easy (I will double check) to get the data for `Biggest transactions table` and `24h statistics`. This two things should be tackled last. The other things should be easy to get 👍

**Comment by a1300** [comment]
Closing
