### ISSUE TITLE
Feature: Search and find for BlockId in Searchbox

### ISSUE THREAD

**Issue by a1300** [GNYIO/gny-explorer#63]

**Comment by xpgeng** [comment]
[This feature](https://github.com/GNYIO/gny-explorer/blob/490d27691404107bb68c8f6ab130d64dd8ca0eb3/components/Search.vue#L83) has been supported. Searching a block by id will be transformed into querying by height.

**Comment by a1300** [comment]
Yes, sorry :+1:
